name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r cloud_functions/requirements.txt

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy ingest function
      run: |
        gcloud functions deploy ingest_f1_data \
          --runtime python39 \
          --trigger-http \
          --source cloud_functions \
          --entry-point ingest_f1_data

    - name: Trigger ingest function
      run: |
        curl -X POST -H "Authorization: Bearer $(gcloud auth print-identity-token)" https://us-central1-weighty-sled-426016-i6.cloudfunctions.net/ingest_f1_data

    - name: Deploy query function
      run: |
        gcloud functions deploy run_query \
          --runtime python39 \
          --trigger-http \
          --source cloud_functions \
          --entry-point run_query

    - name: Trigger query function
      run: |
        curl -X POST -H "Authorization: Bearer $(gcloud auth print-identity-token)" https://us-central1-weighty-sled-426016-i6.cloudfunctions.net/run_query





